# Generated by Django 5.1.6 on 2025-05-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField()),
                ('sender_id', models.CharField()),
                ('chat_id', models.IntegerField()),
                ('text', models.TextField(null=True)),
                ('photo', models.CharField(null=True)),
                ('comment_count', models.CharField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_bot', models.BooleanField(default=False)),
                ('is_restricted', models.BooleanField(blank=True, null=True)),
                ('is_fake', models.BooleanField(blank=True, null=True)),
                ('is_scam', models.BooleanField(blank=True, null=True)),
                ('is_premium', models.BooleanField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='item',
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='items',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Statistic',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Specialty',
        ),
    ]
