# Generated by Django 5.1.6 on 2025-05-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_post_telegramuser_remove_item_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='chat_id',
            field=models.BigIntegerField(default=None),
            preserve_default=False,
        ),
    ]
