# Generated by Django 5.1.6 on 2025-05-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_telegramuser_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='chat_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='sender_id',
            field=models.BigIntegerField(),
        ),
    ]
