# Generated by Django 5.1.6 on 2025-05-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_post_chat_id_alter_post_sender_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='image',
            field=models.CharField(null=True),
        ),
    ]
