# Generated by Django 5.1.6 on 2025-05-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_telegramuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reactions',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='last_seen',
            field=models.CharField(blank=True, null=True),
        ),
    ]
