# Generated by Django 5.1.6 on 2025-05-27 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_telegramuser_ban'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='ban',
            new_name='is_banned',
        ),
    ]
